* ship fw-detect as part of sidux-scripts. * add fw-detect to debian/copyright. * clean up/ re- indent debian/copyright. * remove bogus dependency on udev. * remove dead masquerade script. * switch from custom su-me to generic su-to-root, adapt dependencies and   menu files accordingly. * general clean up.

diff --git a/fix-5b-mouse b/fix-5b-mouse
--- a/fix-5b-mouse
+++ b/fix-5b-mouse
@@ -1,11 +1,11 @@
 #!/bin/sh
 
 if [ "$(id -u)" -ne 0 ]; then
-	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"
-
-	echo Error: You must be root to run this script!
+	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
+	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
 	exit 1
 fi
+
 X_CONF="/etc/X11/xorg.conf"
 
 perl -pi -e 's|(\s*Option\s+"Protocol"\s+)"IMPS/2"|\1"ExplorerPS/2"|'						"$X_CONF"
diff --git a/get-resume-partition b/get-resume-partition
--- a/get-resume-partition
+++ b/get-resume-partition
@@ -1,12 +1,8 @@
 #!/bin/sh
 
 if [ "$(id -u)" -ne 0 ]; then
-	if [ -x /usr/bin/su-me ]; then
-		echo "Please enter root password:"
-		DISPLAY="" exec su-me "$0" "$@"
-	fi
-
-	echo Error: You must be root to run this script!
+	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
+	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
 	exit 1
 fi
 
diff --git a/get-sidux-binary-gfx b/get-sidux-binary-gfx
--- a/get-sidux-binary-gfx
+++ b/get-sidux-binary-gfx
@@ -55,8 +55,8 @@ nuke_me() {
 
 # We have to be root. Oherwise we exit with exitcode 1
 if [ "$(id -u)" -ne 0 ]; then
-	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"
-	echo Error: You must be root to run this script!
+	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
+	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
 	exit 1
 fi
 
diff --git a/remove-gateway b/remove-gateway
--- a/remove-gateway
+++ b/remove-gateway
@@ -1,17 +1,12 @@
 #!/bin/sh
 
 if [ "$(id -u)" -ne 0 ]; then
-	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"
-
-	echo Error: You must be root to run this script!
+	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
+	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
 	exit 1
 fi
 
-if ! test -e /etc/network/interfaces.1st; then
-	cp /etc/network/interfaces /etc/network/interfaces.1st
-fi
-
-perl -pi -e 's/^[\s]*gateway.*[\n]//g' /etc/network/interfaces
+sed -i "/^[ \t]*gateway/d" /etc/network/interfaces
 
 /etc/init.d/networking restart
 
